README Documentation update
Lambda-School-Labs/human-rights-first-ds-c pull request #37
Opened 2020-11-19 21:47 UTC by dondreojordan

2020-11-19 21:48 UTC, sberniz reviewed
Looks good

2020-11-19 22:45 UTC, jlong5795 commented on README.md
> +    *  API URL - API url responsible for updating the database
Should this env have a space in it?

2020-11-19 22:45 UTC, jlong5795 commented on README.md
> +# End Points
I would just link to the live Swagger docs.

2020-11-19 22:46 UTC, jlong5795 commented on README.md
> +| Team Project Lead | Data Scientist | Data Scientist | Web Developer | Web Developer |
Technical Project Lead -> TPL

2020-11-19 22:46 UTC, jlong5795 requested changes
One question, one correction, and one suggestion.

2020-11-19 23:51 UTC, dondreojordan reviewed
Changes have been made. Review ready.

2020-11-19 23:51 UTC, dondreojordan commented on README.md
> +| Team Project Lead | Data Scientist | Data Scientist | Web Developer | Web Developer |
Resolved.

2020-11-19 23:51 UTC, dondreojordan commented on README.md
> +    *  API URL - API url responsible for updating the database
The preview doesn't show this space.

2020-11-20 16:40 UTC, jlong5795 approved these changes
Looks good. Thanks for the updates.

2020-11-20 16:40 UTC, merged